install:
    crash_reporting:
        enabled: true
        type: "crashpad"
    game-settings:
        accountId: 2814007382967680
        modified: false
        timestamp: 0
    gameflow-patcher-lock: 1698015353899
    gameflow-process-info: null
    gameflow-spectate-reconnect-info: null
    globals:
        locale: "en_US"
        region: "NA"
    lcu-settings:
        accountId: 2814007382967680
        modified: false
        timestamp: 0
    patcher:
        client_migrated: true
        client_patcher_available: true
        game_migrated: true
        game_patcher_available: true
        locales:
        - "en_US"
        toggles:
            new_client_patcher: 0
            new_game_patcher: 0
    perks-settings:
        accountId: 2814007382967680
        modified: false
        timestamp: 0
    riotclient-upgrade:
        seq-success-count: 124
        success-count: 124
    rso-auth:
        install-identifier: "568ce02a195b9d4ab04ae91ec791c733"
